apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv
spec:
  storageClassName: {{ .Release.Name }}-mongo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/{{ .Release.Name }}/mongo