---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.service.mysqltag | default (printf "%s-mysql" .Release.Name) }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.mysqltag | default (printf "%s-mysql" .Release.Name) }}
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.service.mysqlimage }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eoloplantsDB
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ .Release.Name }}-datadb
      volumes:
      - name: {{ .Release.Name }}-datadb
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  {{- if .Values.persistentVolumes.createOnInit }} 
  storageClassName: {{ .Release.Name }}-mysql
  {{- else }}
  storageClassName: {{ .Values.mysql.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app: {{ .Values.service.mysqltag | default (printf "%s-mysql" .Release.Name) }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql-port
  selector:
    app: {{ .Values.service.mysqltag | default (printf "%s-mysql" .Release.Name) }}
  type: ClusterIP
{{- if .Values.netpol.enabled }}  
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mysql-from-server
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.service.mysqltag | default (printf "%s-mysql" .Release.Name) }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.service.servertag | default (printf "%s-server" .Release.Name) }}
    ports:
    - port: 3306
      protocol: TCP
{{- end -}}