---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.service.plannertag | default (printf "%s-planner" .Release.Name) }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.plannertag | default (printf "%s-planner" .Release.Name) }}
        {{ .Release.Name }}-dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-planner
        image: {{ .Values.service.plannerimage }}
        env:
        - name: TOPO_HOST
          value: {{ .Release.Name }}-toposervice-service
        - name: TOPO_PORT
          value: "8080"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://{{ .Release.Name }}-weatherservice-service:9090
        - name: SPRING_RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbitmq-service
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-rabbitmq-secret
              key: password
{{- if .Values.netpol.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-to-rabbit-weather-topo
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.service.plannertag | default (printf "%s-planner" .Release.Name) }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.service.rabbittag | default (printf "%s-rabbitmq" .Release.Name) }}
    ports:
    - port: 5672
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
    ports:
    - port: 9090
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.service.topotag | default (printf "%s-toposervice" .Release.Name) }}
    ports:
    - port: 8080
      protocol: TCP
{{- end -}}