---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
      - name: {{ .Release.Name }}-rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: {{ .Release.Name }}-datarabbit
      volumes:
      - name: {{ .Release.Name }}-datarabbit
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-rabbit-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rabbit-pvc
spec:
  storageClassName: {{ .Release.Name }}-rabbit
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-service
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbitmq-port-5672
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbitmq-port-15672
  selector:
    app: {{ .Release.Name }}-rabbitmq
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-rabbitmq-from-planner-server
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-planner
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-server
    ports:
    - port: 5672
      protocol: TCP
