apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-rabbit-pv
spec:
  storageClassName: {{ .Release.Name }}-rabbit
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/{{ .Release.Name }}/rabbitmq