---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  password: {{ ( .Values.mysql.password | default (randAlphaNum 20)) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  password: {{ ( .Values.mongodb.password | default (randAlphaNum 20)) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
type: Opaque
{{ $pass := .Values.rabbitmq.password | default (randAlphaNum 20) -}}
data:
  password: {{ $pass | b64enc }}
  url: {{ (printf "amqp://root:%s@%s-rabbitmq-service" $pass .Release.Name) | b64enc }}