---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
        {{ .Release.Name }}-dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-server
        image: oscarsotosanchez/server:v1.0
        command: ["bash"]
        args:
        - "-c"
        - "./wait-for-it.sh {{ .Release.Name }}-mysql-service:3306 -t 500 -- ./wait-for-it.sh {{ .Release.Name }}-rabbitmq-service:5672 -t 500 -- node src/server.js"
        env:
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql-service
        - name: MYSQL_DB
          value: eoloplantsDB
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: password
        - name: RABBITMQ_URL
          value: amqp://root:password@{{ .Release.Name }}-rabbitmq-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
  labels:
    app: {{ .Release.Name }}-server
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: server-port
  selector:
    app: {{ .Release.Name }}-server
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.ingress.type }}
  {{- end }}
{{- if .Values.netpol.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-to-mysql-rabbit
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-server
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-mysql
    ports:
    - port: 3306
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-rabbitmq
    ports:
    - port: 5672
      protocol: TCP
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-from-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-server
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
{{- else }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-from-nodeport
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-server
  ingress:
    - ports:
      - port: 3000
{{- end -}}
{{- end -}}