apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-toposervice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-toposervice
        {{ .Release.Name }}-dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-toposervice
        image: oscarsotosanchez/toposervice:v1.0
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: {{ .Release.Name }}-mongodb-service
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-toposervice-service
  labels:
    app: {{ .Release.Name }}-toposervice
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: toposervice-port
  selector:
    app: {{ .Release.Name }}-toposervice
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.ingress.type }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-to-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-mongodb
    ports:
    - port: 27017
      protocol: TCP
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-from-planner-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-planner
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
{{- else }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-from-nodeport
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  ingress:
    - ports:
      - port: 8080
{{- end -}}