---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weatherservice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-weatherservice
        image: {{ .Values.service.weatherimage }}
        env:
        - name: GRPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: "9090"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weatherservice-service
  labels:
    app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: weatherservice-port
  selector:
    app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
  type: ClusterIP
{{- if .Values.netpol.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-weather-from-planner
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.service.weathertag | default (printf "%s-weatherservice" .Release.Name) }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.service.plannertag | default (printf "%s-planner" .Release.Name) }}
    ports:
    - port: 9090
      protocol: TCP
{{- end -}}